services:
  # Application
  mc-vanilla:
    container_name: ${CONTAINER_NAME}
    restart: always
    stdin_open: TRUE
    tty: TRUE
    image: itzg/minecraft-server
    env_file:
      - .env
      - secret.env
    environment:
      TZ: Asia/Tokyo
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    dns:
      - ${LOCAL_DNS}
      - 8.8.8.8
      - 1.1.1.1
      - 100.100.100.100
    volumes:
      - ./minecraft/data:/data
      - ./image/server-icon.png:/data/server-icon.png
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      resources:
        limits:
          cpus: 7.0
          memory: 32.0G

  # Backup
  backup:
    restart: unless-stopped
    image: itzg/mc-backup
    depends_on:
      - mc-vanilla
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
      BACKUP_NAME: "${CONTAINER_NAME}-backup"
      BACKUP_INTERVAL: 12h
      BACKUP_METHOD: "tar"
      BACKUP_ON_STARTUP: TRUE
      PRUNE_BACKUPS_DAYS: 5
      PAUSE_IF_NO_PLAYERS: TRUE
      PLAYERS_ONLINE_CHECK_INTERVAL: 5m
      INITIAL_DELAY: 2m
      RCON_HOST: localhost
      RCON_PASSWORD: ${PASSWD}
      SERVER_HOST: ${SERVER_HOST_NAME}
      CRON_SCHEDULE: "0 12 * * *"
      CRON_BACKUP_UID: 1000
      DEST_DIR: /data
      LINK_LATEST: false
      TAR_COMPRESS_METHOD: gzip
      ZSTD_PARAMETERS: "-3 --long=25 --single-thread"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: "service:mc-vanilla"
