services:
  # Application
  mc-vanilla: 
    container_name: ${CONTAINER_NAME}
    restart: always
    stdin_open: TRUE
    tty: TRUE
    image: itzg/minecraft-server
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
      EULA: TRUE
      ENABLE_ROLLING_LOGS: TRUE
      VERSION: ${VERSION} # or "latest"
      TYPE: "VANILLA"
      DIFFICULTY: "hard"
      LEVEL: "world"
      MOTD: "✋(◉ ω ◉｀)よお"
      MAX_PLAYERS: 30
      MAX_WORLD_SIZE: 12000
      ENABLE_RCON: TRUE
      RCON_PASSWORD: ${PASSWD}
      ENABLE_COMMAND_BLOCK: TRUE
      FORCE_WORLD_COPY: TRUE
      SNOOPER_ENABLED: FALSE
      VIEW_DISTANCE: 50
      SIMULATION_DISTANCE: 100
      GAMEMODE: "survival"
      PVP: TRUE
      ANNOUNCE_PLAYER_ACHIEVEMENTS: TRUE
      OVERRIDE_ICON: TRUE
      ENABLE_WHITELIST: TRUE
      MAX_THREADS: 8
      INIT_MEMORY: 4G
      MAX_MEMORY: 24G
      JVM_OPTS: "-XX:MaxRAMPercentage=95 -Xms24576M -Xmx24576M -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:MaxInlineLevel=15"
      # Plugins
      # VERSION: ${VERSION} # or "latest"
      # TYPE: "SPIGOT"
      # PLUGINS_FILE: "./plugins.txt"
    ports:
      - "25565:25565"
    dns:
      - ${LOCAL_DNS}
      - 8.8.8.8
      - 100.100.100.100
    volumes:
      - ./minecraft/data:/data
      - ./images/server-icon.png:/data/server-icon.png
      - /etc/timezone:/etc/timezone:ro
    deploy:
      resources:
        limits:
          cpus: 8
          memory: 24.0G
  
  # Backup
  backup:
    restart: always
    image: itzg/mc-backup
    depends_on:
      - mc-vanilla
    environment:
      TZ: Asia/Tokyo
      BACKUP_NAME: "${CONTAINER_NAME}-backup"
      BACKUP_INTERVAL: 12h
      BACKUP_METHOD: "tar"
      BACKUP_ON_STARTUP: TRUE
      PRUNE_BACKUPS_DAYS: 5
      PAUSE_IF_NO_PLAYERS: TRUE
      PLAYERS_ONLINE_CHECK_INTERVAL: 5m
      INITIAL_DELAY: 2m
      RCON_HOST: localhost
      RCON_PASSWORD: ${PASSWD}
      SERVER_HOST: ${SERVER_HOST_NAME}
    volumes:
      - ./minecraft/backup/data:/data
    network_mode: "service:mc-vanilla"

volumes:
  data: {}
