services:
  # Application
  mc-vanilla: 
    container_name: ${CONTAINER_NAME}
    restart: always
    stdin_open: TRUE
    tty: TRUE
    # image: itzg/minecraft-server:latest
    image: marctv/minecraft-papermc-server:latest
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    dns:
      - ${LOCAL_DNS}
      - 8.8.8.8
      - 100.100.100.100
    volumes:
      - ./minecraft/data:/data
      - ./image/server-icon.png:/data/server-icon.png
      - /etc/timezone:/etc/timezone:ro
    deploy:
      resources:
        limits:
          cpus: 6
          memory: 16.0G
    command: >
      sh -c "
      /start &
      SERVER_PID=$$!
      sleep 30
      sed -i 's/allow-piston-duplication: false/allow-piston-duplication: true/' /data/config/paper-global.yml
      wait $$SERVER_PID
      "
  
  # Backup
  backup:
    restart: always
    image: itzg/mc-backup
    depends_on:
      - mc-vanilla
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
      BACKUP_NAME: "${CONTAINER_NAME}-backup"
      BACKUP_INTERVAL: 12h
      BACKUP_METHOD: "tar"
      BACKUP_ON_STARTUP: TRUE
      PRUNE_BACKUPS_DAYS: 5
      PAUSE_IF_NO_PLAYERS: TRUE
      PLAYERS_ONLINE_CHECK_INTERVAL: 5m
      INITIAL_DELAY: 2m
      RCON_HOST: localhost
      RCON_PASSWORD: ${PASSWD}
      SERVER_HOST: ${SERVER_HOST_NAME}
    volumes:
      - ./minecraft/backup/data:/data
    network_mode: "service:mc-vanilla"

volumes:
  minecraft: 