---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: denkettle
  name: denkettle
spec:
  # never more than 1 since denkettle is not horizontally scalable
  replicas: 1
  serviceName: denkettle
  selector:
    matchLabels:
      app: denkettle
  template:
    metadata:
      labels:
        app: denkettle
    spec:
      containers:
        - name: main
          image: marctv/minecraft-papermc-server
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: k8s-configmap
            - secretRef:
                name: k8s-secret
          volumeMounts:
            - mountPath: /data
              name: data
          ports:
            - containerPort: 25565
              protocol: TCP
              name: minecraft
            - containerPort: 25575
              protocol: TCP
              name: rcon
          readinessProbe: &probe
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe: *probe
          tty: true
          stdin: true
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
# This service is replaced by the one in networking.yaml
# Keep for reference or remove after testing
apiVersion: v1
kind: Service
metadata:
  name: denkettle-internal
spec:
  type: ClusterIP
  selector:
    app: denkettle
  ports:
    - port: 25565
      protocol: TCP
    - port: 25575
      protocol: TCP