---
# Minecraft Service for Tailscale VPN access
# NodePort service for direct external access via Tailscale VPN
apiVersion: v1
kind: Service
metadata:
  name: denkettle-svc
  labels:
    app: denkettle
spec:
  type: NodePort
  selector:
    app: denkettle
  ports:
    - name: minecraft-tcp
      port: 25565
      targetPort: 25565
      protocol: TCP
      nodePort: 25565  # Fixed external port for Minecraft
    - name: rcon
      port: 25575
      targetPort: 25575
      protocol: TCP
      nodePort: 25575  # Fixed external port for RCON
---
# Internal ClusterIP service for pod-to-pod communication
apiVersion: v1
kind: Service
metadata:
  name: denkettle-internal
  labels:
    app: denkettle
spec:
  type: ClusterIP
  selector:
    app: denkettle
  ports:
    - name: minecraft-tcp
      port: 25565
      targetPort: 25565
      protocol: TCP
    - name: rcon
      port: 25575
      targetPort: 25575
      protocol: TCP